# .streamlit/config.toml

[theme]
base = "dark"
primaryColor = "#4DB6AC"             # teal accent — modern, calm
backgroundColor = "#121212"          # very dark gray background
secondaryBackgroundColor = "#1E1E1E" # slightly lighter gray for panels
textColor = "#E0E0E0"                # soft white for readability
font = "sans serif"
